# Generated by Django 3.0 on 2019-12-07 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleprice', models.PositiveIntegerField(default=100000)),
                ('rv', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('number', models.PositiveSmallIntegerField(default=24)),
                ('periodicity', models.PositiveSmallIntegerField(choices=[(0, 'Months'), (3, 'Quarters'), (12, 'Years')], default=0)),
                ('mode', models.PositiveSmallIntegerField(choices=[(0, 'Find'), (1, 'Fixed')], default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_steps', to='quote.Schedule')),
            ],
        ),
    ]
